### ISSUE TITLE
Allow the user to enter their username and password interactively

### ISSUE THREAD

**Issue by christopher-haueter** [tradel/appd-download-bot#2]
It's a security concern that a user's username and password be recorded in plaintext in their shell history.

To avoid leaking my AppD username and password in my shell history when using AppDynamicsDownloader, I would like the downloader to interactively prompt me for my username and password.

**Comment by tradel** [comment]
Good news! I finally got around to adding this in commit c0311a2e6bfbb672db06ab7e39281e1e61783b7d.

Within a few minutes you should be able to do `pip install --upgrade AppDynamicsDownloader` to get the latest version.
